### ISSUE TITLE
Please add support change package name by file options.json

### ISSUE THREAD

**Issue by eaui1997** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#10]
Please add support change package name by file options.json
You can refer to j-hc, he has support change package name by file options.json
The syntax is
[
  {
    "patchName": "Custom package name",
    "options": [
      {
        "key": "YouTubePackageName",
        "value": "custom.youtube.com"
      }
    ]
  }
]

**Comment by FiorenMas** [comment]
Thanks for your suggestion. I have updated it. You can now edit the "option.json" file in the `/src/options` folder to choose the patches you want to use (ReX or Revanced). Then, edit the same options.json file.

**Comment by eaui1997** [comment]
Thank you very much ❤️❤️❤️

**Comment by eaui1997** [comment]
> Thanks for your suggestion. I have updated it. You can now edit the "option.json" file in the `/src/options` folder to choose the patches you want to use (ReX or Revanced). You should fork the repo and edit the same options.json file, then run github action to patch for yourself forgot: if you want change package name you should include patch name "change-package-name" in my `patches` folder, read more at Wiki

1 more question, how i patch with other app version? Like, recommend version is 18.34.37 but i want to patch version 18.33.35

**Comment by FiorenMas** [comment]
Open file `src/build/Revanced.sh` or `ReX.sh`
Delete line `get_ver "Video ads" "com.google.android.youtube"`
And replace it by line `version="18.33.35"`

**Comment by eaui1997** [comment]
Awesome, thank you 💯 👍

**Comment by rahaaatul** [comment]
> [
> {
> "patchName": "Custom package name",
> "options": [
> {
> "key": "YouTubePackageName",
> "value": "custom.youtube.com"
> }
> ]
> }
> ]

Do you think it's correct format to add in options?

```
[
    {
        "patchName": "Custom package name",
        "options": [
            {
                "key": "PackageNameYouTube",
                "value": "app.rvx.android.youtube"
            }
        ]
    },
    {
        "patchName": "Custom branding icon YouTube",
        "options": [
            {
                "key": "AppIcon",
                "value": "Revancify Blue"
            }
        ]
    }
]
```

**Comment by FiorenMas** [comment]
> > [
> > {
> > "patchName": "Custom package name",
> > "options": [
> > {
> > "key": "YouTubePackageName",
> > "value": "custom.youtube.com"
> > }
> > ]
> > }
> > ]
> 
> Do you think it's correct format to add in options?
> 
> ```
> [
>     {
>         "patchName": "Custom package name",
>         "options": [
>             {
>                 "key": "PackageNameYouTube",
>                 "value": "app.rvx.android.youtube"
>             }
>         ]
>     },
>     {
>         "patchName": "Custom branding icon YouTube",
>         "options": [
>             {
>                 "key": "AppIcon",
>                 "value": "Revancify Blue"
>             }
>         ]
>     }
> ]
> ```

yes, but I exclude this patch for default youtube icon, you should remove this exclude patch.
