### ISSUE TITLE
Geçmişi kaydetmiyor 

### ISSUE THREAD

**Issue by hllsvrn** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#14]
Video geçmişi kaydetmiyor. Short videoları kaydediyor yalnızca ama video kaydetmiyor

**Comment by FiorenMas** [comment]
English only. I using google translate know a little what you mean. History not saved it's a bug from revanced, and already fix in Beta version Revanced

**Comment by hllsvrn** [comment]
Do I need to use the beta version?

**Comment by FiorenMas** [comment]
Why not? Read the readme please and download use it
