### ISSUE TITLE
Revanced Facebook getting calls while Revanced messenger is installed. 

### ISSUE THREAD

**Issue by angelicachao** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#17]
Hello, I googled and found that Facebook receives calls when it doesn't  think messenger is installed, though all of the other messenger functions of Revanced Facebook lead to Revanced messenger properly, I'm getting the call notification from both apps whenever I get called now. Is there a way to fix this?

**Comment by kameno22** [comment]
Doable notification for original Facebook Messenger

**Comment by FiorenMas** [comment]
This is a bug caused by Revanced patches. Unfortunately, I can't fix it myself. You should report the issue in their repository. However, I believe Facebook detects Messenger because both apps share the same certificate for signing their APK files. This makes it very difficult for Revanced to fix.

**Comment by angelicachao** [comment]
Thank you for the explanation
