### ISSUE TITLE
Query on Keystore

### ISSUE THREAD

**Issue by rahaaatul** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#18]
What Keystore are you using to patch the apps? Is it from Revancify or Revanced, or are you using another keystore?

**Comment by FiorenMas** [comment]
All of them using offical Revanced keystore but Revanced Extended by inotia00, Revanced Extended Android 6,7 and Revanced Extended 5 I using old keystore another use current keystore, because before Revanced cli v3.1.1 or inotia cli, using another type keystore.
