### ISSUE TITLE
Facebook Ads

### ISSUE THREAD

**Issue by CrazyBytesVE** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#22]
In the published version of Facebook beta, ads continue to appear. I don't know if Revanced blocks them, but I don't see any changes with the official Facebook version.

**Comment by FiorenMas** [comment]
I got feedback about FB latest version have bug about video player too, so I think we should downgrade version FB to v449.0.0.44.115 and waitting new Revanced patches.
