### ISSUE TITLE
Bản beta mới của revanced đã ra nhưng không thấy build

### ISSUE THREAD

**Issue by duc2ht** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#23]
Mình thấy bản beta 2 mới của revanced đã ra nhưng không thấy build tự động, thử build tay cũng thấy báo lỗi

**Comment by FiorenMas** [comment]
> Mình thấy bản beta 2 mới của revanced đã ra nhưng không thấy build tự động, thử build tay cũng thấy báo lỗi

Bản beta của revanced đang bị lỗi, chi tiết xem thêm tại:
https://github.com/ReVanced/revanced-patches/pull/3243#issuecomment-2139372954
