### ISSUE TITLE
Adding More and Bug

### ISSUE THREAD

**Issue by vicjeremy** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#27]
Instagram revanced only block ads or there is another patches?
and try add this: 
[ReVanced Extended (rufusin)](https://github.com/rufusin/revanced-patches)
[YT Advanced (REX)](https://github.com/YT-Advanced/ReX-patches)

**Comment by FiorenMas** [comment]
Readme has full information about patches applied (only Revanced).
![image](https://github.com/user-attachments/assets/945b96fa-64bc-4c96-9d25-413692d0a0b7)
https://revanced.app/patches?s=com.instagram.android
