### ISSUE TITLE
Videos 

### ISSUE THREAD

**Issue by Aleksandrt6** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#28]
![Screenshot_20240906_123711_YouTube](https://github.com/user-attachments/assets/378281c5-1c65-4962-ba78-8883835c8cc7)
, need assistance with playback ID , just what operation,   Stuck play that is problem

**Comment by FiorenMas** [comment]
Missing information needs to be suggested to you, such as which Revanced version you use. And then the issue irrelevant this repository.
