### ISSUE TITLE
Override Patch Selections

### ISSUE THREAD

**Issue by rahaaatul** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#29]
Every time you make changes in your repo syncing in my repo is hard.

Add a new folder exactly similar to `src/patches` config folders To add our own include/exclude patches that will override the default patch configs if any.

That way, it won't conflict with default patch config, and no conflict with syncing repo.

What do you think?

**Comment by FiorenMas** [comment]
I rarely change src/patches so it can sync fork without any conflict...
