### ISSUE TITLE
Chapters not visible in full screen video landscape

### ISSUE THREAD

**Issue by karthikvijay5227** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#3]
Selecting the chapters for videos in landscape mode full screen video is not possible in YouTube revanced but it is possible in revanced extended.Please explain the steps to enable it if there is any.I hope you reply soon.

**Comment by FiorenMas** [comment]
> Selecting the chapters for videos in landscape mode full screen video is not possible in YouTube revanced but it is possible in revanced extended.Please explain the steps to enable it if there is any.I hope you reply soon.

You can enable button to show chapters by: In Youtube Revanced > Setting > Revanced (Revanced specific settings) > Layout > Disable setting "Hide quick actions in fullscreen"

**Comment by karthikvijay5227** [comment]
Thank you so much for your reply.It worked and actually I am confused of
too much settings and features.By the way,why the app is taking too much of
cache memory approximately 460+MB.Please find any solution in next update.

**Comment by FiorenMas** [comment]
Did you install the “All Architecture” version? This version uses more RAM, so you should use the version that matches your phone’s architecture. Most modern phones use arm64-v8a.
