### ISSUE TITLE
Changing package name of builds

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#35]
So I forked this repository, ran the action, and then when to download the release build and it was having update the official youtube app.

So I do I gp about changing the package being used to make the builds?

**Comment by FiorenMas** [comment]
Sometimes apkmirror blocked download because Cloudflare, this lead can't download correct version of youtube. That why that failed to patch. Just wait and try again later. See log build for more details
