### ISSUE TITLE
Patching anddea stable always failed

### ISSUE THREAD

**Issue by GitGitu79** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#39]
It's always failed at 'patch apk'. What could be the cause?

here's the github action log
[logs_32416997538.zip](https://github.com/user-attachments/files/18240932/logs_32416997538.zip)

**Comment by FiorenMas** [comment]
fixed in https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/commit/0af0ae52e3f5ba8399e104dce07f7ce1e13eaad8
