### ISSUE TITLE
Clutters in higher refresh rate

### ISSUE THREAD

**Issue by karthikvijay5227** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#4]
The app clutters and lags in higher refresh rates like 120Hz and 144Hz comparing to the original youtube.It can be fixed through update.

**Comment by FiorenMas** [comment]
> The app clutters and lags in higher refresh rates like 120Hz and 144Hz comparing to the original youtube.It can be fixed through update.

 Did you try using Revanced Manager or Revanced CLI? My phone Poco X3 Pro, didn’t have any problem.

**Comment by karthikvijay5227** [comment]
My phone is Samsung Galaxy M52 5G.I haven't used revanced manager on it and
the issues happens very often and original youtube doesn't has the issue.

**Comment by FiorenMas** [comment]
I mean you should try to build the apk from Revanced Manager. If the problem still occurs, this means there is something wrong with the Revanced patch. If not, my code has some problem.

**Comment by FiorenMas** [comment]
no response

**Comment by karthikvijay5227** [comment]
It is appearing sometimes only so I haven't gave any response.
