### ISSUE TITLE
(Not important) Suggestion to create a telegram channel 

### ISSUE THREAD

**Issue by Sudeepxl20** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#6]
Just create telegram channel for better reach and just to give notifications about the updates

Also u can notify users when there is, any major changes like discontinution of RVX or about the status of the project

**Comment by FiorenMas** [comment]
Thank you for the suggestion. I think my repo is too small for it right now, but if it grows bigger, I might change my mind.
