### ISSUE TITLE
Most patches excluded in ReX

### ISSUE THREAD

**Issue by Sudeepxl20** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#7]
Don't know why just checked out there is most of the patches missing (excluded) in the build

https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/releases/download/all/youtube-arm64-v8a-ReX.apk

Solve this issue and include all the patches form the source so users can have the choice to use the features 
![Screenshot_20230806_234000](https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/assets/111219466/4e9f676a-a2c5-4ce9-8c75-e0ec6555ba40)
![Screenshot_20230806_234008](https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/assets/111219466/0e9956b4-65ed-464b-94a4-4891c28d039a)

**Comment by FiorenMas** [comment]
I excluded some patches for general use. If you want a custom patch, please read the FAQ.
https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/blob/main/docs/Frequently%20Asked%20Questions.md

**Comment by Sudeepxl20** [comment]
Hey what if I want to patch only 1single app and delete (or exclude) other apps, how to do it

**Comment by Sudeepxl20** [comment]
Just a suggestion giving all the patches in upstream is a good, If all. Patches are included we can just share this repo to my family without forking and redoing it for my self, consider adding all the patches (Except the problematic ones like debugging)


Having more features is good idea than crating multiple forks it's a waste of resources also......
