### ISSUE TITLE
ReX patches are not up to date 

### ISSUE THREAD

**Issue by Sudeepxl20** [FiorenMas/Revanced-And-Revanced-Extended-Non-Root#8]
ReX patch Version is old the latest version of Rex is v2.187.2

But the patches information shows v2.187.1

Latest version link https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.187.2
![IMG_20230806_235335](https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/assets/111219466/99d9eae9-4b89-4da7-a409-c412749ee38c)

Include all the availbe patches see #7

**Comment by FiorenMas** [comment]
I think the display patch from ReX is incorrect. My build logs show that I already downloaded the latest patch.
![image](https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/assets/102145692/8b3cc3be-cc99-4656-9930-f7cc18b1655c)

**Comment by Sudeepxl20** [comment]
Hey what if I want to patch only 1single app and delete (or exclude) other apps, how to do it
